### ISSUE TITLE
database creation code?

### ISSUE THREAD

**Issue by rpodcast** [stoltzmaniac/Medicare#1]
I just saw your post on the shiny app and I'm very intrigued by the possibilities.  I see that you've created a sqlite database that's loaded in to the app.  Perhaps I missed it but could you share the code you used to create the database?

Slight tangent but I think this app has great potential and I'd be interested in collaborating further.  I have built many shiny applications at work (I wish I could share them but they are extremely confidential) and I am about to start a series of episodes for my [podcast](https://r-podcast.org) on enhancing shiny applications from the user interface and backend perspectives.  I think working on this application would be a great showcase of how we can incrementally build and improve shiny applications.  If that sounds like something you'd like to pursue [let me know](https://r-podcast.org/contact)!

**Comment by stoltzmaniac** [comment]
Thanks so much! I will certainly get in touch with you about this. As for the SQLite db, I must have accidentally left it in there, I tend to turn csv files into SQLite simply for speed when I'm tinkering around and must not have saved it. I have a full schedule until June 1 but then I can start to add some fun features.

**Comment by stoltzmaniac** [comment]
@thercast take a look at the work @ginberg has put into this. I think it takes care of it.

**Comment by stoltzmaniac** [comment]
Hi @thercast I went ahead and added this code - it is now located in the global.R file. However, due to the size of the csv document online, I commented it out and it can be used when updates are required.

medicare.csv.data = read.csv('https://data.medicare.gov/api/views/77hc-ibv8/rows.csv?accessType=DOWNLOAD')
con = dbConnect(RSQLite::SQLite(),dbname='medicare.sqlite')
dbWriteTable(con,'medicare',value=medicare.csv.data)
